env: "smaclite"

env_args:
  map_name: null
  time_limit: 150
  use_cpp_rvo2: True

test_greedy: True
test_nepisode: 100
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
